export const skills = [
	{
		id: 1,
		title: 'React',
		level: 'average',
		icon: 'logo/react.avif',
		type: 'frontend',
	},
	{
		id: 2,
		title: 'Next.js',
		level: 'average',
		icon: 'logo/nextjs.avif',
		type: 'frontend',
	},
	{
		id: 11,
		title: 'Node.js',
		level: 'average',
		icon: 'logo/nodejs.avif',
		type: 'backend',
	},
	{
		id: 16,
		title: 'SCSS',
		level: 'average',
		icon: 'logo/scss.avif',
		type: 'frontend',
	},
	{
		id: 22,
		title: 'Tailwind',
		level: 'average',
		icon: 'logo/tailwind.avif',
		type: 'frontend',
	},
	{
		id: 23,
		title: 'Bootstrap',
		level: 'average',
		icon: 'logo/bootstrap.avif',
		type: 'frontend',
	},
	{
		id: 24,
		title: 'MaterialUI',
		level: 'average',
		icon: 'logo/mui.avif',
		type: 'frontend',
	},
	{
		id: 25,
		title: 'ShadCN',
		level: 'average',
		icon: 'logo/shadcn.avif',
		type: 'frontend',
	},
	{
		id: 12,
		title: 'Nest.js',
		level: 'basic',
		icon: 'logo/nestjs.avif',
		type: 'backend',
	},
	{
		id: 13,
		title: 'Magento 2',
		level: 'basic',
		icon: 'logo/magento.avif',
		type: 'backend',
	},
	{
		id: 7,
		title: 'PostgreSQL',
		level: 'average',
		icon: 'logo/postgresql.avif',
		type: 'database',
	},

	{
		id: 6,
		title: 'MySQL',
		level: 'average',
		icon: 'logo/mysql.avif',
		type: 'database',
	},
	{
		id: 8,
		title: 'MongoDB',
		level: 'basic',
		icon: 'logo/mongodb.avif',
		type: 'database',
	},
	{
		id: 9,
		title: 'Sequelize',
		level: 'basic',
		icon: 'logo/sequelize.avif',
		type: 'database',
	},
	{
		id: 10,
		title: 'Prisma',
		level: 'average',
		icon: 'logo/prisma.avif',
		type: 'database',
	},
	{
		id: 3,
		title: 'Typescript',
		level: 'average',
		icon: 'logo/typescript.avif',
		type: 'language',
	},
	{
		id: 4,
		title: 'JS',
		level: 'average',
		icon: 'logo/js.avif',
		type: 'language',
	},
	{
		id: 5,
		title: 'PHP',
		level: 'average',
		icon: 'logo/php.avif',
		type: 'language',
	},
	{
		id: 14,
		title: 'HTML',
		level: 'advanced',
		icon: 'logo/html.avif',
		type: 'frontend',
	},
	{
		id: 15,
		title: 'CSS',
		level: 'advanced',
		icon: 'logo/css.avif',
		type: 'frontend',
	},
	{
		id: 17,
		title: 'REST API',
		level: 'average',
		icon: 'logo/restapi.avif',
		type: 'backend',
	},
	{
		id: 18,
		title: 'GraphQL',
		level: 'average',
		icon: 'logo/graphql.avif',
		type: 'backend',
	},
	{
		id: 19,
		title: 'ExpressJS',
		level: 'average',
		icon: 'logo/express.avif',
		type: 'backend',
	},
	{
		id: 20,
		title: 'Socket.io',
		level: 'basic',
		icon: 'logo/socketio.avif',
		type: 'backend',
	},
	{
		id: 21,
		title: 'Redis',
		level: 'average',
		icon: 'logo/redis.avif',
		type: 'backend',
	},
	{
		id: 26,
		title: 'Redux',
		level: 'average',
		icon: 'logo/redux.avif',
		type: 'frontend',
	},
	{
		id: 27,
		title: 'MobX',
		level: 'average',
		icon: 'logo/mobx.avif',
		type: 'frontend',
	},
	{
		id: 28,
		title: 'Zustand',
		level: 'average',
		icon: 'logo/zustand.avif',
		type: 'frontend',
	},
	{
		id: 29,
		title: 'Auth.js',
		level: 'average',
		icon: 'logo/authjs.avif',
		type: 'frontend',
	},
	{
		id: 30,
		title: 'RHF',
		level: 'average',
		icon: 'logo/rhf.avif',
		type: 'frontend',
	},
	{
		id: 31,
		title: 'Webpack',
		level: 'average',
		icon: 'logo/webpack.avif',
		type: 'devtools',
	},
	{
		id: 32,
		title: 'Vite',
		level: 'average',
		icon: 'logo/vite.avif',
		type: 'devtools',
	},
	{
		id: 33,
		title: 'Docker',
		level: 'average',
		icon: 'logo/docker.avif',
		type: 'devtools',
	},
	{
		id: 34,
		title: 'Git',
		level: 'average',
		icon: 'logo/git.avif',
		type: 'devtools',
	},
];

export const levels = [
	{
		en: 'advanced',
		ru: 'Продвинутый',
	},
	{
		en: 'average',
		ru: 'Средний',
	},
	{
		en: 'basic',
		ru: 'Базовый',
	},
];

export const types = [
	'language',
	'frontend',
	'backend',
	'database',
	'devtools',
];
