export const skills = [
	{
		id: 1,
		title: 'React',
		level: 'average',
		icon: 'logo/react.png',
		type: 'frontend',
	},
	{
		id: 2,
		title: 'Next.js',
		level: 'average',
		icon: 'logo/nextjs.png',
		type: 'frontend',
	},
	{
		id: 11,
		title: 'Node.js',
		level: 'average',
		icon: 'logo/nodejs.png',
		type: 'backend',
	},
	{
		id: 16,
		title: 'SCSS',
		level: 'average',
		icon: 'logo/scss.png',
		type: 'frontend',
	},
	{
		id: 22,
		title: 'Tailwind',
		level: 'average',
		icon: 'logo/tailwind.png',
		type: 'frontend',
	},
	{
		id: 23,
		title: 'Bootstrap',
		level: 'average',
		icon: 'logo/bootstrap.png',
		type: 'frontend',
	},
	{
		id: 24,
		title: 'MaterialUI',
		level: 'average',
		icon: 'logo/mui.png',
		type: 'frontend',
	},
	{
		id: 25,
		title: 'ShadCN',
		level: 'average',
		icon: 'logo/shadcn.png',
		type: 'frontend',
	},
	{
		id: 12,
		title: 'Nest.js',
		level: 'basic',
		icon: 'logo/nestjs.png',
		type: 'backend',
	},
	{
		id: 13,
		title: 'Magento 2',
		level: 'basic',
		icon: 'logo/magento.png',
		type: 'backend',
	},
	{
		id: 7,
		title: 'PostgreSQL',
		level: 'average',
		icon: 'logo/postgresql.png',
		type: 'database',
	},

	{
		id: 6,
		title: 'MySQL',
		level: 'average',
		icon: 'logo/mysql.png',
		type: 'database',
	},
	{
		id: 8,
		title: 'MongoDB',
		level: 'basic',
		icon: 'logo/mongodb.png',
		type: 'database',
	},
	{
		id: 9,
		title: 'Sequelize',
		level: 'basic',
		icon: 'logo/sequelize.png',
		type: 'database',
	},
	{
		id: 10,
		title: 'Prisma',
		level: 'average',
		icon: 'logo/prisma.png',
		type: 'database',
	},
	{
		id: 3,
		title: 'Typescript',
		level: 'average',
		icon: 'logo/typescript.png',
		type: 'language',
	},
	{
		id: 4,
		title: 'JS',
		level: 'average',
		icon: 'logo/js.png',
		type: 'language',
	},
	{
		id: 5,
		title: 'PHP',
		level: 'average',
		icon: 'logo/php.png',
		type: 'language',
	},
	{
		id: 14,
		title: 'HTML',
		level: 'advanced',
		icon: 'logo/html.png',
		type: 'frontend',
	},
	{
		id: 15,
		title: 'CSS',
		level: 'advanced',
		icon: 'logo/css.png',
		type: 'frontend',
	},
	{
		id: 17,
		title: 'REST API',
		level: 'average',
		icon: 'logo/restapi.png',
		type: 'backend',
	},
	{
		id: 18,
		title: 'GraphQL',
		level: 'average',
		icon: 'logo/graphql.png',
		type: 'backend',
	},
	{
		id: 19,
		title: 'ExpressJS',
		level: 'average',
		icon: 'logo/express.png',
		type: 'backend',
	},
	{
		id: 20,
		title: 'Socket.io',
		level: 'basic',
		icon: 'logo/socketio.png',
		type: 'backend',
	},
	{
		id: 21,
		title: 'Redis',
		level: 'average',
		icon: 'logo/redis.png',
		type: 'backend',
	},
	{
		id: 26,
		title: 'Redux',
		level: 'average',
		icon: 'logo/redux.png',
		type: 'frontend',
	},
	{
		id: 27,
		title: 'MobX',
		level: 'average',
		icon: 'logo/mobx.png',
		type: 'frontend',
	},
	{
		id: 28,
		title: 'Zustand',
		level: 'average',
		icon: 'logo/zustand.png',
		type: 'frontend',
	},
	{
		id: 29,
		title: 'Auth.js',
		level: 'average',
		icon: 'logo/authjs.png',
		type: 'frontend',
	},
	{
		id: 30,
		title: 'RHF',
		level: 'average',
		icon: 'logo/rhf.png',
		type: 'frontend',
	},
	{
		id: 31,
		title: 'Webpack',
		level: 'average',
		icon: 'logo/webpack.png',
		type: 'devtools',
	},
	{
		id: 32,
		title: 'Vite',
		level: 'average',
		icon: 'logo/vite.png',
		type: 'devtools',
	},
	{
		id: 33,
		title: 'Docker',
		level: 'average',
		icon: 'logo/docker.png',
		type: 'devtools',
	},
	{
		id: 34,
		title: 'Git',
		level: 'average',
		icon: 'logo/git.png',
		type: 'devtools',
	},
];

/*
- basic
- average
- advanced
*/
